version: "3.7"

services:
  notebook:
    build:
      context: ./Jupyter
      dockerfile: Dockerfile
    image: notebook:latest
    ports: 
      - "8888:8888"
    volumes: 
      - ./notebooks:/home/jovyan/work

